<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="liyl" ignored="0" name="YXT" tests="5" failures="1" timestamp="21 十一月 2020 08:33:41 GMT" time="2.782" errors="0">
  <testcase name="test001_login" time="0.209" classname="com.yxt.testcases.login.LoginTests"/>
  <testcase name="test002_login" time="1.302" classname="com.yxt.testcases.login.LoginTests"/>
  <testcase name="test001_getDataPermissionList" time="0.127" classname="com.yxt.testcases.dataPermission.GetDataPermissionListTests">
    <failure type="java.lang.AssertionError" message="expected [dp_325038] but found [dp_1325038]">
      <![CDATA[java.lang.AssertionError: expected [dp_325038] but found [dp_1325038]
at com.yxt.testcases.dataPermission.GetDataPermissionListTests.test001_getDataPermissionList(GetDataPermissionListTests.java:37)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_getDataPermissionList -->
  <testcase name="test002_getDataPermissionList" time="0.055" classname="com.yxt.testcases.dataPermission.GetDataPermissionListTests"/>
  <testcase name="test003_getDataPermissionCount" time="0.035" classname="com.yxt.testcases.dataPermission.GetDataPermissionListTests"/>
</testsuite> <!-- YXT -->
